package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.pedropathing.follower.Follower;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.seattlesolvers.solverslib.command.CommandOpMode;
import com.seattlesolvers.solverslib.command.SequentialCommandGroup;
import com.seattlesolvers.solverslib.command.WaitCommand;

import org.firstinspires.ftc.teamcode.Subsystems.FlowerIntake;
import org.firstinspires.ftc.teamcode.pedro.Constants;

@Autonomous
public class Auto extends CommandOpMode {
    private Follower follower; // you added this before
    private OurPaths ourPaths;

    @Override
    public void initialize() {
        super.reset();

        follower = Constants.create(hardwareMap);
        ourPaths = new OurPaths(follower);
        FlowerIntake flowerIntake= new FlowerIntake(this);

        schedule(
            new SequentialCommandGroup(
            ourPaths.pathToFlower1(),
            flowerIntake.onCommand(),
            new WaitCommand(3000),
            flowerIntake.offCommand(),
            ourPaths.pathToShoot(),
            flowerIntake.reverseCommand(),
            new WaitCommand(3000),
            flowerIntake.offCommand()



        ));
    }

    @Override
    public void run() {
        super.run();
        follower.update();

        telemetry.addData("X", follower.pose().x());
        telemetry.addData("Y", follower.pose().y());
        telemetry.addData("Heading", Math.toDegrees(follower.pose().heading()));
        telemetry.addData("Follower Mode", follower.mode());
        telemetry.update();
    }
}
