package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.ivy.Scheduler;

import static com.pedropathing.ivy.Scheduler.schedule;

@Autonomous
public class ExampleAuto extends OpMode {
    private Follower follower; // you added this before
    private OurPaths ourPaths;

    @Override
    public void init() {
        Scheduler.reset();
        follower = Constants.create(hardwareMap);
        ourPaths = new OurPaths(follower);
    }

    @Override
    public void start() {
        schedule(ourPaths.PathToFlower());
    }

    @Override
    public void loop() {
        Scheduler.execute();
        follower.update();

        telemetry.addData("X", follower.pose().x());
        telemetry.addData("Y", follower.pose().y());
        telemetry.addData("Heading", Math.toDegrees(follower.pose().heading()));
        telemetry.addData("Follower Mode", follower.mode());
        telemetry.update();
    }
}
