package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;
import com.pedropathing.ivy.Scheduler;

import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;

import static com.pedropathing.ivy.Scheduler.schedule;

@Autonomous
public class ExampleAuto extends OpMode {
    private Follower follower; // you added this before
    private final PoseFactory p = PoseFactory.degrees();

    private OurPaths ourPaths;

    private final Pose startPose = p.of(24, 24, 0);
    private final Pose park = p.of(48, 48, 90);
    // other poses...
    private final Pose controlPose = p.of(36, 60, 45);
    private final Pose controlPoseTwo = p.of(40, 60, 45);

    private Path park() {
        return line(startPose, park).linear(startPose, park);
    }

    private Path parkTurn() {
        return curve(startPose, controlPose, park).linear(startPose, park);
    }

    @Override
    public void init() {
        Scheduler.reset();

        follower = Constants.create(hardwareMap);
        ourPaths = new OurPaths(follower);
    }

    @Override
    public void start() {
        schedule(ourPaths.new PathToFlower().autoRoutine());
    }

    @Override
    public void loop() {
        follower.update();
        Scheduler.execute();

        telemetry.addData("X", follower.pose().x());
        telemetry.addData("Y", follower.pose().y());
        telemetry.addData("Heading", Math.toDegrees(follower.pose().heading()));
        telemetry.addData("Follower Mode", follower.mode());
        telemetry.update();
    }
}
